web:
    image: nginx:latest
    ports:
        - "8000:80"
    volumes:
        - ./code:/code
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    build: ./fpm7/
    volumes:
        - ./code:/code
    links:
      - memcacheq
      - memcacheq
memcacheq:
    image: wupeng/memcacheq:0.2.0
memcache:
    image: memcached:latests
