web:
    image: nginx:latest
    ports:
        - "8000:80"
    volumes:
        - ./code:/code
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    build: ./fpm7/
    volumes:
        - ./code:/code
    links:
      - memcacheq
      - memcache
      - mysql
memcacheq:
    image: wupeng/memcacheq:0.2.0
memcache:
    image: memcached:latest
mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pinnport
      - MYSQL_DATABASE=pinnport
      - MYSQL_USER=pinnport
      - MYSQL_PASSWORD=pinnport
    volumes:
      - ./db_data:/var/lib/mysql
