web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./code:/code
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    build: ./fpm7/
    volumes:
        - ./code:/code
    links:
      - memcache
      - mysql
      - sq
sq:
    image: schickling/beanstalkd
memcache:
    image: memcached:latest
mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pinnport
      - MYSQL_DATABASE=pinnport
      - MYSQL_USER=pinnport
      - MYSQL_PASSWORD=pinnport
    volumes:
      - ./db_data:/var/lib/mysql
